#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

CONTAINER_USER_FILE=${SCRIPT_DIR}/.env
if [ -f "${CONTAINER_USER_FILE}" ]; then
  touch ${CONTAINER_USER_FILE}
fi

# Write the host UID and GID to a file that can be read by Docker Compose
echo "# This file is auto-generated by set-up-container-user.sh" > ${CONTAINER_USER_FILE}
echo "HOST_UID=$(id -u)" >> ${CONTAINER_USER_FILE}
echo "HOST_GID=$(id -g)" >> ${CONTAINER_USER_FILE}
