name: ROS 2 build

on:
  push:
  pull_request:

jobs:
  colcon-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy]
        demo:
          - hello_clearpath
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base
    name: ${{ matrix.demo }} (${{ matrix.ros_distro }})
    steps:
      - uses: actions/checkout@v6
        with:
          path: src/clearpath_community_demos
      - name: Import extra demo sources (if any)
        shell: bash
        run: |
          repos_file=src/clearpath_community_demos/demos/${{ matrix.demo }}/${{ matrix.demo }}.repos
          if [[ -f "$repos_file" ]]; then
            apt-get update
            apt-get install -y python3-vcstool
            vcs import src < "$repos_file"
          fi
      - name: Install rosdep dependencies
        shell: bash
        run: |
          apt-get update
          rosdep update
          rosdep install \
            --from-paths src/clearpath_community_demos/demos/${{ matrix.demo }} \
            --ignore-src -r -y
      - name: Build
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          colcon build --packages-up-to ${{ matrix.demo }}
